Add getter and setter for the "Averaging and Sampling Configuration" register
adafruit/Adafruit_CircuitPython_CAP1188 pull request #17
Opened 2020-07-29 12:52 UTC by jeremiahrose

Fixes issue #16 

The methods provide (/ accept) a triple containing the three
parameters required to fully specify the register: avg, samp_time
and cycle_time.
This allows the user to tweak the responsiveness of the CAP1188.

2020-08-17 19:35 UTC, kattni commented
@jeremiahrose The checks are failing on this PR. Please check out this guide for the steps necessary to deal with the formatting checks: https://learn.adafruit.com/improve-your-code-with-pylint Let me know if you need any assistance!

2020-08-17 21:18 UTC, ladyada commented
i reviewed for style but not physical test - im ok merging once CI passes!

2020-08-28 00:01 UTC, makermelissa commented
Hi @jeremiahrose, would you please run black code formatter on this? It should get to the next stage of checks after that. Thanks

2020-11-24 17:11 UTC, dherrada commented
@ladyada Are you still okay with merging this once CI passes?

2020-11-24 17:46 UTC, ladyada commented
id like someone to test it with hardware first

2020-11-24 17:54 UTC, dherrada commented
@ladyada I'd be willing to, but it'd take a few days since I don't have the hardware.

2020-12-16 21:25 UTC, dherrada requested changes
It did work exactly as it was supposed to, but I do think that it should be reorganized for ease of use and readability.

2020-12-16 21:25 UTC, dherrada commented on adafruit_cap1188/cap1188.py
> +    def averaging(self):
Split the two methods you added into three separate pairs of functions, so 6 functions total. Have each set of functions handle one of the things you can set in register 0x24. That way the user won't have to pass all three values if they only want to set one. Basically, have the setter functions read the register, then only change the bits pertinent to that specific setting and then write to the register.

An alternative way to do this without creating any more functions would be to have the user pass up to 3 values to the setter function, making the default value of each None, and then reading from the register and only modifying the bits that the user wants to change. Personally, I prefer the first option, but I'd be okay with the second.

2020-12-16 21:25 UTC, dherrada commented on adafruit_cap1188/cap1188.py
> +        the sample time, and the cycle time."""
Say what the default values of each of these are

2021-05-03 10:56 UTC, jposada202020 commented
@dherrada, person involved in this has not longer the hardware to do any development, so I think we have to options:
1. Accept the PR as is, something that you don not like very much
2. I could do the changes that you mentioned, however I do not have this hardware. So testing needs to be done by other folk.
What do you think?

2021-05-03 17:07 UTC, dherrada commented
@jposada202020 If you'd like to, take a crack at making those changes and I'll test, but if you don't want to I can make them myself although finals are starting soon for me so I might not be able to get to it for a bit

2021-05-03 17:35 UTC, jposada202020 commented
No worries Ill take it, No more finals in my life :) @dherrada

2021-05-03 17:43 UTC, dherrada commented
Lucky you lol

2021-05-03 22:19 UTC, jposada202020 commented
@dherrada I am so sorry for the delay in getting back to you :), in #21 are the changes, if `soon` does not mean starting tomorrow, I think we are good to go. thanks 👍🏼

2021-05-04 17:27 UTC, dherrada commented
@jposada202020 No worries. My only final is Saturday and I'm already decently well prepared for it anyways.

2021-05-04 22:13 UTC, dherrada commented
@jposada202020 Want to test this when your gets in?

2021-05-04 22:19 UTC, jposada202020 commented
Yes I would! Thanks @dherrada

2021-05-10 19:07 UTC, jposada202020 commented
Closed. Changes with made after work from @jeremiahrose on PR #21

2021-05-10 19:07 UTC, closed without merging