Add initial functionality
adafruit/Adafruit_CircuitPython_CAP1188 pull request #2
Opened 2018-09-25 20:57 UTC by caternuson

Basic I2C and SPI functionality in place.
**NOTE:** CAP1188 pins start at 1 - indexing matches pins.
```python
cap[1].value
cap[1].raw_value
```
Along with ability to recalibrate:
```python
cap.recalibrate()     # recal all pins
cap[1].recalibrate()  # recal just pin 1
```
**NOT INCLUDED**
* reset pin
* irq pin
* many other knobs

2018-09-26 02:10 UTC, sommersoft requested changes
Took a gander. Code looks good to me. Found just a few things to help Travis's mood once its setup.

For the example filenames, I _think_ the standard is to include "simpletest". But, that may be a call better left to @kattni.

Note: I **did not** test this, as I don't have the sensor available.

2018-09-26 02:10 UTC, sommersoft commented on docs/index.rst
> +.. todo:: Add any Learn guide links here. If there are none, then simply delete this todo and leave
Travis, once setup, will trip on this todo.

2018-09-26 02:10 UTC, sommersoft commented on docs/index.rst
> +.. todo:: Add any product links here. If there are none, then simply delete this todo and leave
Same as above.

2018-09-26 02:10 UTC, sommersoft commented on docs/conf.py
> +# autodoc_mock_imports = ["digitalio", "busio"]
You'll need to uncomment, and mock `micropython`.

2018-09-26 02:10 UTC, sommersoft commented on docs/examples.rst
> +.. literalinclude:: ../examples/cap1188_simpletest.py
This doesn't match the actual example files.

2018-10-02 19:53 UTC, caternuson commented on docs/examples.rst
> +.. literalinclude:: ../examples/cap1188_simpletest.py
Example changed to be more standardy. Now it should.

2018-10-02 23:51 UTC, sommersoft commented
@adafruit/circuitpythonlibrarians does anyone have a CAP1188 sensor to test this with? I sadly, do not...so my approval stops at that point. ☹️

2018-10-03 00:16 UTC, ladyada commented on adafruit_cap1188/cap1188.py
> +        return self._read_register(CAP1188_MANU_ID)
i think this is swapped with the manuf id above?

2018-10-03 00:17 UTC, ladyada requested changes

2018-10-03 00:17 UTC, ladyada commented on adafruit_cap1188/cap1188.py
> +        return self._read_register(CAP1188_REVISION)
swapped with rev register below?

2018-10-03 00:17 UTC, ladyada commented
i can do the hardware test, but have some requested changes/fixes!

2018-10-03 00:23 UTC, caternuson commented on adafruit_cap1188/cap1188.py
> +        return self._read_register(CAP1188_MANU_ID)
:man_facepalming:

2018-10-03 00:23 UTC, caternuson commented on adafruit_cap1188/cap1188.py
> +        return self._read_register(CAP1188_REVISION)
:man_facepalming:

2018-10-03 02:21 UTC, ladyada requested changes

2018-10-03 02:21 UTC, ladyada commented on examples/cap1188_simpletest.py
> +# cap = CAP1188_I2C(spi, cs)
you mean SPI here!

2018-10-03 02:24 UTC, ladyada requested changes

2018-10-03 02:24 UTC, ladyada commented on adafruit_cap1188/cap1188.py
> +        self._channels = [None]*8
check the manufacturer id and product id here to verify the chip is wired correctly

2018-10-03 02:36 UTC, ladyada commented
id actually remove the properties for manufacturer, reveision etc and just check register values in init(), you'll never need that data again. you can see bme280 library for how we exception on failure

2018-10-03 03:04 UTC, caternuson commented on examples/cap1188_simpletest.py
> +# cap = CAP1188_I2C(spi, cs)
mmmm. copypasta.

2018-10-03 06:02 UTC, ladyada commented on adafruit_cap1188/cap1188.py
> +        self._channels = [None]*8
thankx!

2018-10-03 06:02 UTC, ladyada approved these changes

2018-10-03 06:03 UTC, ladyada commented
ok this library tests fine by me, good enough for v1.0.0 - we can add more stuff if people request it :)

2018-10-03 15:47 UTC, kattni approved these changes
Everything appears to be set with this, I'm going to go ahead and merge. Thanks @caternuson for doing this and thanks everyone for your reviews!

2018-10-03 15:48 UTC, merged